apiVersion: v1
kind: Service
metadata:
  name: tanzuapp-service
spec:
  type: NodePort
  selector:
    app: tanzuapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31000  # Rango 30000-32767
